document.write("Rules for naming JS variables:");
document.write("<br>");
document.write("a) A heading stating “Rules for naming JS variables”");
document.write("<br>");
document.write("Variable names can only contain letters , numbers , $ and _ .");
document.write("<br>");
document.write("Variables must begin with a $ , _ or a letter.");
document.write("<br>");
document.write("Variable names are case sensitive");
document.write("<br>");
document.write("Variable names should not be JS keywords");